from flask import Flask, render_template, request, Response
import json
import io
import zipfile

app = Flask(__name__)

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/generate', methods=['POST'])
def generate_script():
    # Get plugins from checkboxes
    selected_plugins = request.form.getlist('plugins')
    custom_plugins_str = request.form.get('custom_plugins', '')
    custom_plugins = [slug.strip() for slug in custom_plugins_str.splitlines() if slug.strip()]
    all_plugins = sorted(list(set(selected_plugins + custom_plugins)))

    # Get Elementor global style settings from form
    global_styles = {
        'color_primary': request.form.get('color_primary', '#6EC1E4'),
        'color_secondary': request.form.get('color_secondary', '#54595F'),
        'color_text': request.form.get('color_text', '#7A7A7A'),
        'color_accent': request.form.get('color_accent', '#61CE70'),
        'font_primary': request.form.get('font_primary', 'Roboto'),
        'font_secondary': request.form.get('font_secondary', 'Roboto Slab'),
        'font_text': request.form.get('font_text', 'Roboto'),
        'font_accent': request.form.get('font_accent', 'Roboto'),
    }

    # Create the site settings JSON structure
    site_settings = {
        "system_colors": [
            {"_id": "primary", "title": "Primary", "color": global_styles['color_primary']},
            {"_id": "secondary", "title": "Secondary", "color": global_styles['color_secondary']},
            {"_id": "text", "title": "Text", "color": global_styles['color_text']},
            {"_id": "accent", "title": "Accent", "color": global_styles['color_accent']}
        ],
        "custom_colors": [],
        "system_typography": [
            {"_id": "primary", "title": "Primary Headline", "typography_typography": "custom", "typography_font_family": global_styles['font_primary'], "typography_font_weight": "600"},
            {"_id": "secondary", "title": "Secondary Headline", "typography_typography": "custom", "typography_font_family": global_styles['font_secondary'], "typography_font_weight": "400"},
            {"_id": "text", "title": "Body Text", "typography_typography": "custom", "typography_font_family": global_styles['font_text'], "typography_font_weight": "400"},
            {"_id": "accent", "title": "Accent Text", "typography_typography": "custom", "typography_font_family": global_styles['font_accent'], "typography_font_weight": "500"}
        ],
        "custom_typography": []
    }

    # Create the manifest JSON structure
    manifest = {
        "name": "ai-wp-starter-kit",
        "title": "AI WP Starter Kit",
        "description": "Configuration generated by the AI WP Starter Kit tool.",
        "version": "1.0.0",
        "author": "AI Agent",
        "export_type": "local",
        "content": [],
        "templates": [],
        "site-settings": ["__elementor-kit-site-settings.json"],
        "plugins": all_plugins
    }

    # Create a zip file in memory
    memory_file = io.BytesIO()
    with zipfile.ZipFile(memory_file, 'w', zipfile.ZIP_DEFLATED) as zf:
        zf.writestr('manifest.json', json.dumps(manifest, indent=4))
        zf.writestr('__elementor-kit-site-settings.json', json.dumps(site_settings, indent=4))
    memory_file.seek(0)

    # Create a response to send the zip file
    return Response(
        memory_file,
        mimetype='application/zip',
        headers={'Content-Disposition': 'attachment;filename=elementor-kit.zip'}
    )

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000)
