from flask import Flask, render_template, request, Response

app = Flask(__name__)

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/generate', methods=['POST'])
def generate_script():
    # Get plugins from checkboxes
    selected_plugins = request.form.getlist('plugins')

    # Get custom plugins from textarea
    custom_plugins_str = request.form.get('custom_plugins', '')
    custom_plugins = [slug.strip() for slug in custom_plugins_str.splitlines() if slug.strip()]

    # Combine the lists and remove duplicates
    all_plugins = sorted(list(set(selected_plugins + custom_plugins)))

    if not all_plugins:
        script_content = "#!/bin/bash\n# No plugins selected.\necho \"No plugins were selected to install.\"\n"
    else:
        # Generate the script content
        script_content = "#!/bin/bash\n\n"
        script_content += "# This script was generated by the AI_WP_Starter_Kit_Generator.\n"
        script_content += "# It installs and activates a list of WordPress plugins using WP-CLI.\n\n"
        script_content += 'echo "Starting plugin installation..."\n\n'

        for plugin in all_plugins:
            script_content += f'echo "Installing and activating {plugin}..."\n'
            script_content += f"wp plugin install {plugin} --activate\n"
            script_content += 'echo "----------------------------------------"\n\n'

        script_content += 'echo "All plugins have been installed and activated successfully."\n'

    # Create a response to send the file
    response = Response(script_content, mimetype='text/x-shellscript')
    response.headers.set('Content-Disposition', 'attachment', filename='install_plugins.sh')

    return response

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000)
